version: '3.8'

services:
  redis_discord:
    image: redis:latest
    ports: ["6379:6379"]
    networks: [backend]

  redis_wikipedia:
    image: redis:latest
    ports: ["6380:6379"]
    networks: [backend]

  zookeeper:
    image: manios/zookeeper:3.4.5
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks: [backend]
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost:2181"]
      interval: 120s
      timeout: 60s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "19092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
    networks: [backend]
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 10

  discord_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.discord
    env_file:
      - ../config/discord_bot/.env
    depends_on:
      kafka:
        condition: service_healthy
      redis_discord:
        condition: service_started

  wikipedia:
    build:
      context: ..
      dockerfile: docker/Dockerfile.wikipedia
    env_file:
      - ../config/wikipedia/.env
    depends_on:
      kafka:
        condition: service_healthy
      redis_wikipedia:
        condition: service_started

networks:
  backend: