FROM golang:latest AS build

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY ./config/wikipedia/.env /app/.env

RUN go build -o main ./cmd/wikipedia

FROM alpine:latest

WORKDIR /app

COPY --from=build /app/main /app/main
COPY --from=build /app/.env /app/.env

CMD ["./main"]