FROM golang:latest AS build

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main ./cmd/discord_bot

FROM alpine:latest

WORKDIR /app

COPY --from=build /app/main /app/main

CMD ["./main"]