// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: pkg/proto/wikipedia/wikipedia.proto

package wikipedia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wikipedia_wikipedia_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wikipedia_wikipedia_proto_rawDescGZIP(), []int{1}
}

type SetLanguageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLanguageRequest) Reset() {
	*x = SetLanguageRequest{}
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLanguageRequest) ProtoMessage() {}

func (x *SetLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLanguageRequest.ProtoReflect.Descriptor instead.
func (*SetLanguageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wikipedia_wikipedia_proto_rawDescGZIP(), []int{2}
}

func (x *SetLanguageRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GetLanguageUpdatesResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Updates       []*GetLanguageUpdatesResponse_Data `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLanguageUpdatesResponse) Reset() {
	*x = GetLanguageUpdatesResponse{}
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguageUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguageUpdatesResponse) ProtoMessage() {}

func (x *GetLanguageUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguageUpdatesResponse.ProtoReflect.Descriptor instead.
func (*GetLanguageUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wikipedia_wikipedia_proto_rawDescGZIP(), []int{3}
}

func (x *GetLanguageUpdatesResponse) GetUpdates() []*GetLanguageUpdatesResponse_Data {
	if x != nil {
		return x.Updates
	}
	return nil
}

type GetLanguageUpdatesResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLanguageUpdatesResponse_Data) Reset() {
	*x = GetLanguageUpdatesResponse_Data{}
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguageUpdatesResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguageUpdatesResponse_Data) ProtoMessage() {}

func (x *GetLanguageUpdatesResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wikipedia_wikipedia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguageUpdatesResponse_Data.ProtoReflect.Descriptor instead.
func (*GetLanguageUpdatesResponse_Data) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wikipedia_wikipedia_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetLanguageUpdatesResponse_Data) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetLanguageUpdatesResponse_Data) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_pkg_proto_wikipedia_wikipedia_proto protoreflect.FileDescriptor

var file_pkg_proto_wikipedia_wikipedia_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x69, 0x6b, 0x69,
	0x70, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x77, 0x69, 0x6b, 0x69, 0x70, 0x65, 0x64, 0x69, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a,
	0x12, 0x53, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22,
	0xbc, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f,
	0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x1a,
	0x5d, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x32, 0x9c,
	0x01, 0x0a, 0x10, 0x57, 0x69, 0x6b, 0x69, 0x70, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x38, 0x5a,
	0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x62, 0x64, 0x69,
	0x67, 0x61, 0x6c, 0x69, 0x61, 0x72, 0x73, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6f, 0x6e, 0x2d, 0x67,
	0x61, 0x6d, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x69,
	0x6b, 0x69, 0x70, 0x65, 0x64, 0x69, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_proto_wikipedia_wikipedia_proto_rawDescOnce sync.Once
	file_pkg_proto_wikipedia_wikipedia_proto_rawDescData []byte
)

func file_pkg_proto_wikipedia_wikipedia_proto_rawDescGZIP() []byte {
	file_pkg_proto_wikipedia_wikipedia_proto_rawDescOnce.Do(func() {
		file_pkg_proto_wikipedia_wikipedia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_wikipedia_wikipedia_proto_rawDesc), len(file_pkg_proto_wikipedia_wikipedia_proto_rawDesc)))
	})
	return file_pkg_proto_wikipedia_wikipedia_proto_rawDescData
}

var file_pkg_proto_wikipedia_wikipedia_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_wikipedia_wikipedia_proto_goTypes = []any{
	(*EmptyRequest)(nil),                    // 0: auth.EmptyRequest
	(*EmptyResponse)(nil),                   // 1: auth.EmptyResponse
	(*SetLanguageRequest)(nil),              // 2: auth.SetLanguageRequest
	(*GetLanguageUpdatesResponse)(nil),      // 3: auth.GetLanguageUpdatesResponse
	(*GetLanguageUpdatesResponse_Data)(nil), // 4: auth.GetLanguageUpdatesResponse.Data
	(*timestamppb.Timestamp)(nil),           // 5: google.protobuf.Timestamp
}
var file_pkg_proto_wikipedia_wikipedia_proto_depIdxs = []int32{
	4, // 0: auth.GetLanguageUpdatesResponse.updates:type_name -> auth.GetLanguageUpdatesResponse.Data
	5, // 1: auth.GetLanguageUpdatesResponse.Data.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: auth.WikipediaService.SetLanguage:input_type -> auth.SetLanguageRequest
	0, // 3: auth.WikipediaService.GetLanguageUpdates:input_type -> auth.EmptyRequest
	1, // 4: auth.WikipediaService.SetLanguage:output_type -> auth.EmptyResponse
	3, // 5: auth.WikipediaService.GetLanguageUpdates:output_type -> auth.GetLanguageUpdatesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_wikipedia_wikipedia_proto_init() }
func file_pkg_proto_wikipedia_wikipedia_proto_init() {
	if File_pkg_proto_wikipedia_wikipedia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_wikipedia_wikipedia_proto_rawDesc), len(file_pkg_proto_wikipedia_wikipedia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_wikipedia_wikipedia_proto_goTypes,
		DependencyIndexes: file_pkg_proto_wikipedia_wikipedia_proto_depIdxs,
		MessageInfos:      file_pkg_proto_wikipedia_wikipedia_proto_msgTypes,
	}.Build()
	File_pkg_proto_wikipedia_wikipedia_proto = out.File
	file_pkg_proto_wikipedia_wikipedia_proto_goTypes = nil
	file_pkg_proto_wikipedia_wikipedia_proto_depIdxs = nil
}
